# dependabot config for npm

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "wednesday"
    groups:
      lint:
        patterns:
          - "eslint*"
          - "@eslint*"
          - "globals"
          - "typescript-eslint"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      
