name: 'Repos-Topiccloud'
description: 'Creates a wordcloud from the repo topics for the action user'
inputs:
  github-token:
    description: 'GitHub Secret Token'
    required: true

runs:
  using: 'node16'
  pre: 'version.js'
  main: 'dist/index.js'