name: 'Repos-Topiccloud'
description: 'Creates a wordcloud from the repo topics for the action user'
inputs:
  github-token:
    description: 'GitHub Secret Token'
    required: true
  test-login:
    description: 'login to test with'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'