name: Test Cloud

on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 'lts/*'
    - name: Install
      run: |
        pnpm install
    - name: Test
      run: |
        npm run testcloud
        cat cloud-test.svg
   
