name: Test Cloud

on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        npm ci
        tsc
    - name: Test
      run: |
        npm run testcloud
   
